server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8091
          predicates:
            - Path=/api/admin/**

        - id: customer_route
          uri: http://localhost:8092
          predicates:
            - Path=/api/customer/**

        - id: membership_route
          uri: http://localhost:8093
          predicates:
            - Path=/api/membership/**

        - id: package_route
          uri: http://localhost:8094
          predicates:
            - Path=/api/package/**

        - id: trainer_route
          uri: http://localhost:8095
          predicates:
            - Path=/api/trainer/**